# Note: make sure that the value of c_stdlib_version (MACOSX_DEPLOYMENT_TARGET)
# in `conda_build_config.yaml` stays synchronized with `macos-platform.patch`
# and/or what upstream expects in the scikit-build config in its
# `pyproject.toml` file.

# Also note: due to the way the software is packaged, these Python bindings
# cannot reuse the shared library provided by the `openexr` package, as far as I
# can tell. So this package is actually independent of that one, but builds a
# lot of the same C++ code.

{% set name = "OpenEXR" %}
{% set version = "3.4.14" %}

package:
  name: openexr-python  # distinguish from the `openexr` C++ library package
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 40eb9446c5b722ee9d012a4935273210e07b86639fd5f89413523979ba438914
  patches:
    - macos-platform.patch  # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - imath
    - libdeflate
    - openjph
    - pip
    - pybind11
    - python
    - scikit-build-core <1.0  # upstream not compatible as of 3.4.13 (2026 Aug); can probably relax this soon
    - zlib
  run:
    - numpy
    - python

test:
  imports:
    - Imath
    - OpenEXR
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.excamera.com/sphinx/articles-openexr.html
  summary: Python bindings for ILM's OpenEXR image file format
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - pkgw
